title: Muhammad Hashir Arif
description: Mechanical engineering student | CAD & FEA | Control systems and MATLAB simulations
author:
  name: Muhammad Hashir Arif
  email: hashirarif234@gmail.com

social:
  github: https://github.com/MuhammadHashir-sudo/MuhammadHashir-sudo.github.io
  linkedin: www.linkedin.com/in/muhammad-hashir-arif-mechanical-engineer-video-editor-graphic-designer

theme: jekyll-theme-minimal

